flags: {}
extra-package-dbs: []
packages:
- '.'
- location:
   git: https://github.com/paul-rouse/mysql-simple
   commit: 87d9deaeea5984b51af1bc1c9425ecd333990d8e
   extra-dep: true
extra-deps:
- mysql-0.1.2.1
resolver: lts-7.1
